<div class="about_banner">
  <div class="container">
   <div class="about_banner_img">
       <img src="<?php echo $this->getSkinUrl('images/about_banner.jpg'); ?>"/>
   </div>
   <div class="about_banner_text">
       <p>M&W Fashion Pvt. Ltd. Started  its journey on August 2015. The first M&W store was launched in Saltlake, at City Centre – I . We have already opened four Retail Showroom at City Centre , Burrabazar, Park Street, Rangoli Mall, Raghav Plaza (Hawrah AC), Durgapur (JCT Mall) & Acropolis Mall.</p>
       <p>We also have an EBO of Jockey at Avani River Side Mall since 2012
</p>
       <p>In coming days we are looking to be open 100 Showrooms shortly. M&W Fashion Pvt. Ltd. is may be the first multi brand innerwear showroom in Kolkata.</p>
       <p>M&W featured among 20 most-trusted brands all over world.
</p>
   </div>
    </div>
</div>
<div class="our_vision">
    <div class="container">
       <div class="row">
       <div class="col-sm-6">
        <h3>Our Vision</h3>
        <p>To be a premium global conglomerate with a clear focus on each of the businesses.</p>
        </div>
        <div class="col-sm-6">
        <h3>Our Mission</h3>
        <p>To deliver superior value to our customers, employees and society at large.</p>
        </div>
        </div>
        <div class="our_value">
        <h3>Our Values</h3>
        <p>Integrity: Taking decision in a manner that is fair and honest following the highest 
Slandered  of professionalism and being recognized for doing so. Integrity for us means not only financial and intellectual integrity, but encompasses all other forms as are generally understood.</p>
   <p>Commitment: On the foundation of Integrity, doing all that is needed to deliver value to all stakeholders. In the process, being accountable for our own actions and decisions, those of our team and those in the part of the organisation for which we are responsible.</p>
   </div>
   
    </div>
</div>
<div class="co_founder">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <img src="<?php echo $this->getSkinUrl('images/client.jpg'); ?>"/>
            </div>
            <div class="col-sm-6">
                <h3>Our Founder & CEO</h3>
                <h4>Richa Kar</h4>
                <p>In 2011, Richa Kar borrowed Rs. 30 lakh from family and friends to start Zivame, with an aim to change the way women shopped for lingerie in India. From attaining a degree in engineering to engineering bras, she’s come a long way. Her commitment to put the customer first, attention to detail and focus on creating a delightful experience has made Zivame a favourite brand in India and across the globe.</p>

<p>Richa has been featured in Fortune India’s list of ’40 under 40’ and CNBC’s list of ‘Young Business Women - 2016’</p>
           <div class="client_com">
               “Every day my team and I are inspired to create superior products and an elevated experience. If you like Zivame today, it’ll be even better tomorrow.”
               <span>- Richa</span>
           </div>
            </div>
        </div>
    </div>
</div>
<div class="our_investor">
    <h3>Our Investors</h3>
    <div class="container">
    <div class="row">
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="investor_logo">
                <img src="<?php echo $this->getSkinUrl('images/invest1.jpg'); ?>"/>
            </div>
        </div>
    </div>
    </div>
</div>
<div class="our_team">
    <h3>Our Team</h3>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div><div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="team_box">
                    <img src="<?php echo $this->getSkinUrl('images/team1.jpg'); ?>"/>
                    <h4>Venkatesh</h4>
                    <p>Vice President – Operations and Customer Relations</p>
                </div>
            </div>
        </div>
    </div>
</div>


