

<div class="policy_pages">
    <div class="container">
        <h3>Disclaimer and Warranties</h3>
        The materials on m&w.com’s web site are provided “as is”. m&w.com makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, m&w.com does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
    </div>
</div>