

<div class="policy_pages">
    <div class="container">
        <h3>Frequently Asked Questions</h3>
        <p><b>Am I wearing the right bra size?</b></p>
        <p>Most women wear a wrong bra size, which may cause health problems and ruin your look. Check out the below points to know if you are wearing a wrong bra size.</p>
        <ul>
            <li>If your shoulder straps are digging into your shoulders, then you are wearing a tight bra. If they are hanging loose on your shoulders, then you are wearing a loose bra. Move up or down a bra size accordingly to solve this problem. You could also adjust your bra straps so as to get a proper fit.</li>
            <li>You are wearing a wrong bra size if your underwires are poking you. In this case, you could move up a size on your bra band.</li>
            <li>Your bra cups are looking wrinkled over your outfit? Then, you are wearing a larger cup size. You need to go for a smaller cup size to eliminate this problem.</li>
            <li>If our bra band is riding up your back, then you are wearing a bigger band size. In such a case, you can move down a band size to get the right fit.</li>
            </ul>
            <p>The key to choosing the right bra size is to measure yourself properly. With the help of our Bra Calculator, you can be sure to get the right bra size for you.</p>
            
            <p><b>How to avoid breast spillage?</b></p>
            <p>First, make sure your bra band is snug and lies in a straight line across your back. A snug bra band is super important because it provides 90% of your bra’s support! If your band is loose, it may ride up, causing your cups to fall forward, and breast tissue to spill out.</p>
            <p>Adjust your breasts so that all of your breast tissue is inside the cup & the wire. Your underwire should always lie on your body and never dig into breast tissue. It should also sit just around your breast- not down on your belly or over to one side.</p>
            <p>Next, adjust your bra straps so that they are not too tight or too loose. An overly tight strap will yank your cup up and cause unnecessary spillage.</p>
            <p>If you still feel your breasts tissues are spilling out, then you are wearing wrong cup size. You may want to increase a cup size while choosing the right bra for you.</p>
            
            <p><b>How do I overcome breast sagging?</b></p>
            <p>Choose a bra with a wide back strap. The wider the back strap the more support you get in front. This may include bras with 3-6 hooks. You may like the look of a lacy bra with a one hook closure in the back, but it won’t support larger breasts. Fortunately, colorful, lacy, cute and/or sexy supportive bras can now be found in even the largest sizes.</p>
            <p>Choose a bra designed to support large breasts. You may also go for a push-up bra to shape your breasts and avoid breast sagging.</p>
            <p>Wear a supportive sports bra. This is particularly important in sports that have a lot of movement and bouncing like running, soccer (football), rugby etc</p>
            <p>Lean forward when putting on your bra to ensure your chest is centered and perky. Also, make sure the middle of the bra is centered with your body.</p>
            <p>Look for the mid-point on your arm and your nipple line should be level with that middle area of your arm. If it is too low you aren’t getting enough support.</p>
            <p>You have to replace your bras regularly if you want to keep your breasts supported and not saggy. One hint to get the most out of your bras is to buy bras that fit on the loosest hook. As your bra stretches, you can go down to the tighter hooks to prolong the life of the garment. Also remember, you should never put a bra in the dryer! Heat damages the elastic band and causes the bra to lose its support.</p>
            <p><b>I love to wear body hugging outfits, but my weight and size just doesn’t let me. What do I do?</b></p>
            <p>There is a piece of shapewear to fix it. While not the sexiest undergarments, shapewear is certainly a workhorse. Whether you want to boost, or minimize, shapewear helps you put your best foot forward. From hip to knee coverage to full torso shapewear-you can find a piece that smoothes out lines, flattens your tummy and minimizes the jiggle in your wiggle. Ladies that seemingly don’t “need” shapewear, donn this under armor.</p>
            <p><b>My daughter is going through adolescence and I want to give her a peace of mind with the right bra for her. Please help.</b></p>
            <p>Some girls want to wear a bra, others may find the subject embarrassing and want to avoid it for as long as possible. Peer group pressure can often play a part, too. Every girl is going to differ as growth and development is unique to each person.</p>
            <p>As an introduction into bra-wearing, it is advisable to go for a “Starter Bra”. As your daughter’s bust size increases and you both feel it is necessary for her to move on, you will find there is a good variety of starter bras or teenage bras available. Teenage bras differ from adult bras. Although they may have the same band size and cup size, the design will be slightly smaller. Generally:</p>
            <p>– the shoulder straps will be shorter<br>
– the cups will be slightly smaller in depth, and<br>
– the band will not be as deep</p>
       <p>Reflecting that the bra will be being matched not only to the bra size but also to the height and build of teenagers – which will be different to an adult.</p>
       
<p><b></b>For starter bras</b> – it is recommended to choose wire-free (sometimes known as soft cup), rather than underwired bras, which use a U-shaped wire, sewn into the bra cup. In the early stages of puberty, the bust is beginning to develop, the rib cage is developing and a wire-free bra avoids the issues of underwires digging in or chafing.</p>
       <p><b>Sports Bras</b> – For larger teenagers who find teenage bras too small, a sports bra is a recommended option. These are again wire-free & discreet. They look very similar to cropped tops.</p>
       <p><b>Underwired Bras</b> – As teenagers develop, they will inevitably want to wear underwired bras. Underwired bras offer shape, support and the majority of fashion bras out there are underwired.</p>
       <p><b>My breasts size are big and I want to shape them and make them look smaller. What bra do I wear?</b></p>
       <p>In order to give the appearance of smaller breasts you need to see what kind of bra you are wearing. Minimizer Bras are known to minimise the size of breasts. You could also wear a full support bra, which would offer maximum support to the whole breast, shape them and make them look firm.</p>
       <p><b>How do I get my underwired bra to stop poking me?</b></p>
       <p>When it comes to bras, no subject gets more attention than the underwire poking problem. Poking is a sign of a fitting problem. If you are being poked on the inside of your armpit, the bra is probably too large. If you are being poked on the inside of your arm or on the edge of the breast, the bra is probably too small. Move up or down a size on the band. You may also need to adjust the cup size.</p>
       <p><b>I need to know the right panty to wear under right attire. Please guide.</b></p>
       <p>Here are some tips to wear the right panty beneath the right outfit:</p>
       <ul>
           <li>Under a dress you should wear a thong</li>
           <li>Under tight fitting outfits , either a tiny string thong or seamless boyshort brief.</li>
           <li>With white pants, ideally, you should wear a thong—dark colors are a definite no-no, and white-on-white does not work either. A nude colored thong therefore works best.</li>
       </ul>
       <p><b>My panty lines are visible under tight clothes. What type of panty do I wear to avoid this?</b></p>
       <p>Any full-seat panty will ruin the line of a trouser that is well cut and narrow. A seamless boy short provides perfect coverage and are a great alternative to thongs, they go over the butt and the top of the leg to create a completely smooth tush.</p>
        
    </div>
</div>