<div class="banner_section">
 <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="<?php echo $this->getSkinUrl('images/banner.jpg'); ?>"/>
     
    </div>
    <div class="item">
      <img src="<?php echo $this->getSkinUrl('images/banner2.jpg'); ?>"/>
     
    </div>
    <div class="item">
      <img src="<?php echo $this->getSkinUrl('images/banner.jpg'); ?>"/>
    </div>
 
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<div class="say_hello">
   <div class="container">
    <h2><span>Say Hello To</span> The Brand Boutique</h2>
    <p>A curated collection of your favourites - Zivame, Lovable, Triumph & more.</p>
    <a href="#">SEE MORE</a>
    
    <div class="say_hello_image_blog">
        <div class="first_img_blog">
            <div class="first_img_blog_left">
                <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog1.jpg'); ?>"/></a>
            </div>
            <div class="first_img_blog_left">
                <div class="first_img_blog_left_one">
                    <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog2.jpg'); ?>"/></a>
                </div>
                <div class="first_img_blog_left_one">
                    <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog3.jpg'); ?>"/></a>
                </div>
            </div>
        </div>
        <div class="first_img_blog">
           <div class="first_img_blog_left">
                <div class="first_img_blog_left_one">
                    <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog2.jpg'); ?>"/></a>
                </div>
                <div class="first_img_blog_left_one">
                    <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog3.jpg'); ?>"/></a>
                </div>
            </div>
            <div class="first_img_blog_left">
                <a href="#"><img src="<?php echo $this->getSkinUrl('images/blog1.jpg'); ?>"/></a>
            </div>
            
        </div>
    </div>
    </div>
</div>
<div class="follow_my_curves">
    <div class="container">
         <h2><span>Follow My</span> Curves</h2>
    <p>Discover our latest style stories, fit secrets and conversations from our community</p>
    </div>
    <div class="follow_my_curve_slider">
                            <div class="customNavigation">
                                <a class="btn prev"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a>
                                <a class="btn next"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a>
                            </div>
                            <div id="owl-demo" class="owl-carousel">
                                <div class="item">
                                  <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                                <div class="item">
                                    <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                                <div class="item">
                                    <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/slide1.jpg'); ?>"/>
                                      <h3>The Ultimate Bridal Lingerie Checklist</h3>
                                      <p>Find padded bras, babydolls & lace lined panties Styles that make you feel irresistible and sexy</p>
                                      <a href="#">READ MORE</a>
                                  </div>
                                </div>
                            </div>
    </div>
</div>

<div class="pink_bar">
    The Ultimate Bridal Lingerie Checklist The Ultimate 
</div>
<div class="summer_mood">
    <div class="container">
        <h2><span>Fit for Summer</span> Moods</h2>
        <p>Chic, colourful cotton bras made for everyday wear</p>
        <div class="summer_box">
            <div class="row">
                <div class="col-sm-4">
                  <div class="pro_img_text">
                   <div class="pro_text">
                       <p>Zivame Padded Under Wired Push Up Bra- Coral</p>
                       <span>Rs. 745</span>
                   </div>
                    <div class="pro_img">
                        <img src="<?php echo $this->getSkinUrl('images/product1.jpg'); ?>"/>
                    </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="pro_img_text">
                   <div class="pro_text">
                       <p>Zivame Padded Under Wired Push Up Bra- Coral</p>
                       <span>Rs. 745</span>
                   </div>
                    <div class="pro_img">
                        <img src="<?php echo $this->getSkinUrl('images/product1.jpg'); ?>"/>
                    </div>
                    </div>
                </div>
                
                <div class="col-sm-4 col-sm-offset-4">
                  <div class="pro_img_text">
                  <div class="pro_img">
                        <img src="<?php echo $this->getSkinUrl('images/product1.jpg'); ?>"/>
                    </div>
                   <div class="pro_text">
                       <p>Zivame Padded Under Wired Push Up Bra- Coral</p>
                       <span>Rs. 745</span>
                   </div>
                    
                    </div>
                    <div class="clearfix"></div>
                    <div class="pro_img_text">
                     <div class="pro_img">
                        <img src="<?php echo $this->getSkinUrl('images/product1.jpg'); ?>"/>
                    </div>
                   <div class="pro_text">
                       <p>Zivame Padded Under Wired Push Up Bra- Coral</p>
                       <span>Rs. 745</span>
                   </div>
                   
                    </div>
                </div>
            </div>
        </div>
        <div class="shop_collect">
            <a href="#">Shop collection</a>
        </div>
    </div>
</div>
<div class="fit_for_all">
   <div class="container">
    <h2><span>Be The First To See Our TV Ad!</span> FitForAll</h2>
    <p>Through this campaign, we celebrate women and how proudly they accept their bodies. Real and relatable women with different kinds of bodies, come together to showcase how Zivame is #FitForAll. Take a look below!</p>
    <div class="video_play">
        <img src="<?php echo $this->getSkinUrl('images/video.jpg'); ?>"/>
        <div class="video_play_b">
            <a href="#"><span class="glyphicon glyphicon-expand" aria-hidden="true"></span></a>
        </div>
        <div class="watch_video_b">
            <a href="#">WATCH VIDEO</a>
        </div>
    </div>
    </div>
</div>
<div class="pink_bar">
    The Ultimate Bridal Lingerie Checklist The Ultimate 
</div>
<div class="trading_product">
    <div class="container">
        <h2><span>Shop Our Latest</span> Trending Products</h2>
        <div class="trading_product_slider">
            <div class="customNavigation">
                                <a class="btn prev2"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
                                <a class="btn next2"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></span></a>
                            </div>
                            <div id="owl-demo2" class="owl-carousel">
                                <div class="item">
                                  <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                                <div class="item">
                                    <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                                <div class="item">
                                    <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                                <div class="item">
                                   <div class="trading_product_box">
                                      <img src="<?php echo $this->getSkinUrl('images/trading.jpg'); ?>"/>
                                      <div class="trading_product_box_text">
                                          <p>Zivame Goddess Non Stretch Full Coverage Bra-Pink Floral</p>
                                          <div class="price_box">Rs.907 <span>Rs.1295</span></div>
                                          <div class="cart_wish">
                                              <div class="wish_i"><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></div>
                                              <div class="cart_i"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span></div>
                                          </div>
                                      </div>
                                  </div>
                                </div>
                            </div>
        </div>
    </div>
</div>
<div class="latest_scoop">
   <div class="container">
    <h2><span>Check Out Our</span> Latest Scoop</h2>
    <p>What's new, our stores, customer speak and announcements</p>
    <div class="latest_scoop_slider">
        <div class="customNavigation">
                                <a class="btn prev3"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span></a>
                                <a class="btn next3"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></span></a>
                            </div>
                            <div id="owl-demo3" class="owl-carousel">
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="latest_scoop_box">
                                        <div class="latest_scoop_box_text">
                                            <h4>Majorly Crushing On Zivame Bralettes!</h4>
                                            <p>Zivame has the cutest range of bralettes in a variety of colours. Absolutely love the one I’m wearing here, so much that I chose to wear it as a crop top!</p>
                                            <span>-Fashion blogger, Juhi Godambe, on our new range of bralettes.</span>
                                            <div class="line"></div>
                                            <a href="#">Check Out Our Bralettes <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="latest_scoop_box_img">
                                        <img src="<?php echo $this->getSkinUrl('images/latest_s.jpg'); ?>"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
    </div>
    </div>
</div>
<div class="newsletter">
    <div class="container">
        <h2><span>Sign Up to</span> Our Newsletter</h2>
        <p>Get hooked on. Be the first to know about our latest collections and offers.</p>
    </div>
</div>

