

<div class="policy_pages">
    <div class="container">
        <h3>Privacy Policy</h3>
        
        <p><b>Collection of Information</b></p>
        <p>We collect information from you when you register on our site, place an order or fill out a form.
When ordering or registering on our site, as appropriate, you may be asked to enter your name, e-mail address, mailing address, phone number or credit card information. You may, however, visit our site anonymously.</p>
   <p><b>Usage of Information</b></p>
   <p>Any of the information we collect from you may be used in one of the following ways:<br>
To personalize your experience</p>
   <p>Your information helps us to better respond to your individual needs<br>
To improve our website</p>
   <p>We continually strive to improve our website offerings based on the information and feedback we receive from you<br>
To improve customer service</p>
   <p>Your information helps us to more effectively respond to your customer service requests and support needs<br>
       To process transactions</p>
        <p>Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested.<br>
To send periodic emails</p>
   <p>The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.<br>
Protection of Information</p>
   <p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information.
We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.</p>
   <p>After a transaction, your private information (credit cards, social security numbers, financials, etc.) will not be stored on our servers.</p>
   <p><b>Use of Cookies</b></p>
   <p>Yes. Cookies are small files that a site or its service provider transfers to your computer’s hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information.</p>
   <p>We use cookies to help us remember and process the items in your shopping cart, understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.</p>
   <p><b>Confidentiality</b></p>
   <p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>
   <p><b>Third party links</b></p>
   <p>Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>
   <p><b>Online Privacy Policy Only</b></p>
   <p>This online privacy policy applies only to information collected through our website and not to information collected offline.</p>
   <p><b>Terms and Conditions</b></p>
   <p>Please also visit our Terms and Conditions section establishing the use, disclaimers, and limitations of liability governing the use of our website m&w.com/terms-of-use</p>
   <p><b>Changes to our Privacy Policy</b></p>
   <p>If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.</p>
   <p><b>Contacting Us</b></p>
   <p>If there are any questions regarding this privacy policy you may contact us using our <a href="#">Contact Information</a>.</p>
    </div>
</div>