

<div class="policy_pages">
    <div class="container">
        <h3>Refund Policy</h3>
        <p>Kindly let us know immediately, in case you want to return the product and get a refund on it (does not include shipping charges). If you have made an online payment, your refund money will be credited to your account within 7 business days after we receive the product from you. In case you have made a cash-on delivery payment, we will require 15 business days to process the refund, once we receive the product from you.</p>
        <div class="v_spacer20"></div>
        <p>Please make sure that you are returning the product unwashed/free from dirt, along with the product tag, original invoice and original product packaging in the shipping box. Please give a call on 08050017676 & send an e-mail to enquiry@m&w.com to inform us about the returns immediately.</p>
        <div class="v_spacer20"></div>
        <p>The returns can be shipped to following address through your preferred courier service. Your return shipping charges will be re-imbursed.</p>
        
<!--
        
        <p><b>M/S M&WRetails Pvt Ltd.,</b><br>
301,Third floor, Aadishakti Arcade,<br>
Ansurkar galli,<br>
Belgaum-590001</p>
-->
   
   <p><b>DieSachbearbeiter</b><br>
Choriner Straße 49<br>
10435 Berlin<br>
E-Mail: moinsen@blindtextgenerator.com</p>
    </div>
</div>