

<div class="policy_pages">
    <div class="container">
        <h3>Return Policy</h3>
        <p>You are not happy with the product you ordered? It is not fitting you properly? Have we sent an incorrect product to you or is it damaged? In such cases, customers can go for easy and hassle-free returns, in exchange for a different product or a refund (Check <a href="#">Refund Policy</a>)</p>
        <div class="v_spacer20"></div>
        <p>Please go through the following policies for returns of the products delivered to you.</p>
        <p>1. Please return the product within 15 days of delivery. Please ensure you return it with the original packaging & the return slip (Find it at the backside of the invoice)<br>
2. Products such as briefs, swimwear, shapewear, any innerwear set that has brief in it, are not eligible for returns in order to maintain high standards of hygiene.<br>
3. We will not accept the return of a product if it seems to be dirty/washed.<br>
4. We shall not accept individual items when the products are sold as packs.<br>
5. For returning of gifts, refund on gift packing will not be made.<br>
6. No refund policy is applicable on products which are on sale during season promotions / stock clearance.</p>
       <div class="v_spacer20"></div>
       <p>Please make sure that you are returning the product unwashed/free from dirt, along with the product tag, original invoice and original product packaging in the shipping box. Please give a call on 08050017676 or send an e-mail to enquiry@M&W.com to inform us about the returns immediately.</p>
       <div class="v_spacer20"></div>
       <p>The returns can be shipped to following address through your preferred courier service. Your return shipping charges will be re-imbursed.</p>
       
       
       <p><b>DieSachbearbeiter</b><br>
Choriner Straße 49<br>
10435 Berlin<br>
E-Mail: moinsen@blindtextgenerator.com</p>
        
    </div>
</div>