

<div class="policy_pages">
    <div class="container">
        <h3>Shipping Policy</h3>
        <p><b>Which are the courier services you use for the delivery of my order?</b></p>
        <p>We use courier services of First Flight and Blue Dart to deliver your orders.</p>
        <div class="v_spacer20"></div>
        <p><b>Please specify your domestic shipping rates</b></p>
        <p>The rate charged for the shipping of your order is based on the following:</p>
        <div class="row">
            <div class="col-sm-6">
                <p><b>Order Value</b><br>999 and above<br>Below 999<br>For orders above Rs. 999, shipping is absolutely free!</p>
            </div>
            <div class="col-sm-6">
                <p><b>Shipping Charges</b><br>Free Shipping<br>Rs 50.00</p>
            </div>
            
        </div>
        <div class="v_spacer20"></div>
        <p><b>How long would you take to deliver my order?</b></p>
        <p>All orders are shipped within 48 hours. Please note that your order will be delivered within 5-6 business days. Any questions or concerns should be addressed to enquiry@M&W.com. Please include order confirmation number in the subject of email. We make sure to answer all emails within 24 hours.</p>
        <div class="v_spacer20"></div>
        <p><b>What if I receive my order in a damaged condition?</b></p>
        <p>We will absolutely make sure that you receive your order in a good condition. When your order arrives, please inspect the package for any damage that may have occurred during shipment. It is normal for the shipping package to show some wear, however, if damage has been occurred to the items in your shipment, please contact M&W Customer Service at 08050017676 between the hours of 10am to 7pm or send an email enquiry@M&W.com. We will be happy to assist you.</p>
        <p>Please have a look at our <a href="#">Return Policy</a>, if you would like to return the item(s) to us.</p>
        <div class="v_spacer20"></div>
        <p><b>How do I track my orders ?</b></p>
        <p>You can make use of the provision in our website to track your order online.</p>
        <p>Below are some of the steps to trace your order.</p>
        <ul>
            <li>Please check your delivery confirmation or tracking number. This was sent to you from us via email/ sms. Sometimes these emails get sent to your junk/spam folder. Please go to http://www.M&W.com/my-account and track your order. Should you not be able to locate your order please contact us at 08050017676</li>
            <li>Please make absolutely sure that you have given us the correct postal address and email address.</li>
            <li>Please check if your delivery confirmation or tracking number’s time of delivery match your usual time of mail delivery.</li>
            <li>Please check with your neighbor, in case your mail carrier has dropped your package with them or some other place when you aren’t home.</li>
            <li>Please check if they left you a pick up notice.</li>
            <li>Please contact your Postmaster at your post office to get further assistance, and report possible thefts.</li>
        </ul>
    </div>
</div>