
<div class="offer_banner">
<img src="<?php echo $this->getSkinUrl('images/store_banner.jpg'); ?>"/>
</div>

<div class="offer_section">
    <div class="container">
      <div class="store_locate">
       <h2>Kolkata</h2>
       <p>A curated collection of your favourites - M&W, Lovable, Triumph & more.</p>
        <div class="row">
           
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
           
           
        </div>
        </div>
        <div class="store_locate">
        <h2>Howrah</h2>
       <p>A curated collection of your favourites - M&W, Lovable, Triumph & more.</p>
        <div class="row">
           
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
           
           
        </div>
        </div>
        <div class="store_locate">
        <h2>Durgapur</h2>
       <p>A curated collection of your favourites - M&W, Lovable, Triumph & more.</p>
        <div class="row">
           
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="offer_box">
                      <a href="#"><img src="<?php echo $this->getSkinUrl('images/store1.jpg'); ?>"/></a>
                </div>
            </div>
           
           
        </div>
        </div>
    </div>
</div>