<div>
<?php
$collection = Mage::getModel('store/store')->getCollection();
$collection->addFieldToFilter('status','1');
foreach ($collection as $item):
?>
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "store/" . $item->getImage(); ?>" data-thumb="" title="#<?php echo $item->getTitle(); ?>" alt="" data-transition="slideInLeft" />
    <?php echo $item->getDescription();?>
    <a href="<?php echo $item->getUrl(); ?>"><?php echo $this->__('shop now'); ?></a>
<?php endforeach; ?>
</div>